export const productsList = [
  {
    name: 'Heavyweight Black Hoodie',
    description: 'Our signature heavyweight hoodie in classic black. 400gsm fleece-lined cotton, dropped shoulders, kangaroo pocket.',
    price: 89,
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80',
    ],
    category: 'hoodies',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#0a0a0a', '#3a3a3a'],
    stock: 50,
    isFeatured: true,
  },
  {
    name: 'Bone Cream Hoodie',
    description: 'Warm off-white heavyweight hoodie. Relaxed fit with ribbed cuffs and hem. A wardrobe essential.',
    price: 89,
    images: [
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80',
    ],
    category: 'hoodies',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#f5efe0', '#e0d6c2'],
    stock: 40,
    isFeatured: true,
  },
  {
    name: 'Burnt Orange Hoodie',
    description: 'Bold burnt orange colorway. Same heavyweight construction as our signature hoodie, now in a statement color.',
    price: 95,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    ],
    category: 'hoodies',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#ff4d2e', '#cc3a1f'],
    stock: 30,
    isFeatured: true,
  },
  {
    name: 'Forest Green Hoodie',
    description: 'Deep forest green hoodie. Subtle, earthy, and built to last. Goes with everything.',
    price: 95,
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80',
    ],
    category: 'hoodies',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#1f3d2b', '#2c5a3f'],
    stock: 35,
    isFeatured: true,
  },
  {
    name: 'Washed Grey Hoodie',
    description: 'Vintage-washed grey. Soft, pre-worn feel straight out of the bag. Classic streetwear staple.',
    price: 85,
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80',
    ],
    category: 'hoodies',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#9e9e9e', '#757575'],
    stock: 25,
    isFeatured: false,
  },
  {
    name: 'Black Heavyweight Tee',
    description: '280gsm heavyweight cotton t-shirt. Boxy fit, reinforced collar, longer body length.',
    price: 45,
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
    ],
    category: 'tees',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#0a0a0a'],
    stock: 60,
    isFeatured: false,
  },
  {
    name: 'White Essential Tee',
    description: 'Clean white heavyweight tee. The perfect layering piece or standalone summer staple.',
    price: 45,
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
    ],
    category: 'tees',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#ffffff', '#f5f5f5'],
    stock: 55,
    isFeatured: false,
  },
  {
    name: 'Hoodizz Cap',
    description: 'Six-panel structured cap with embroidered HOODIZZ logo. One size fits all with adjustable strap.',
    price: 35,
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&q=80',
    ],
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['#0a0a0a', '#ffffff'],
    stock: 45,
    isFeatured: false,
  },
];
